format = """$env_var$os$username$hostname$kubernetes$directory$git_branch$git_status$python
$character
"""

[character]
success_symbol = ""
error_symbol = ""
# ╭╴ ╰─

[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "$symbol"
disabled = false


#warp-Drop ugly default prompt characters
#success_symbol = ""
#error_symbol = ""

# ---

[os]
format = '[$symbol](bold blue) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

# ---y

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'white bold'
format = '[//](white bold) [$user](#2883ff) ' # 2883ff
disabled = true
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[//](white bold) [$hostname](bold blue) '
disabled = true

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
# read_only_style = '197'
read_only = '  '
format = '[//](white bold) [$path]($style)[$read_only]($read_only_style) '
style = '#7ed1fb' # yellow bold


# Shows current git branch
[git_branch]
# symbol = ' '
symbol = ''
format = '[//](white bold) [$symbol\[$branch\]]($style) '
# truncation_length = 0
# truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
disabled = true
format = '$all_status $ahead_behind($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
symbol = '󰌠'
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = '[//](white bold) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '


[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
